name: Generate GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # twice a day
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: deepakrakshit

          # -------------------------
          # Output
          # -------------------------
          filename: assets/github-metrics.svg
          base: header, activity, community, repositories

          # -------------------------
          # Languages
          # -------------------------
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_details: bytes-size, percentage

          # -------------------------
          # Streak
          # -------------------------
          plugin_streak: yes

          # -------------------------
          # Appearance
          # -------------------------
          config_timezone: Asia/Kolkata
          config_display: large
          config_padding: 0
